# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mapsafe_dialog_base.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_BulkVectorExportDialogBase(object):
    def setupUi(self, BulkVectorExportDialogBase):
        if not BulkVectorExportDialogBase.objectName():
            BulkVectorExportDialogBase.setObjectName(u"BulkVectorExportDialogBase")
        BulkVectorExportDialogBase.resize(544, 489)
        self.tabWidget = QTabWidget(BulkVectorExportDialogBase)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(20, 50, 511, 431))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget_2 = QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(10, 60, 501, 351))
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget_4 = QTabWidget(self.tab_4)
        self.tabWidget_4.setObjectName(u"tabWidget_4")
        self.tabWidget_4.setGeometry(QRect(20, 16, 601, 311))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.horizontalSlider_min = QSlider(self.tab_3)
        self.horizontalSlider_min.setObjectName(u"horizontalSlider_min")
        self.horizontalSlider_min.setGeometry(QRect(30, 30, 160, 22))
        self.horizontalSlider_min.setOrientation(Qt.Horizontal)
        self.horizontalSlider_max = QSlider(self.tab_3)
        self.horizontalSlider_max.setObjectName(u"horizontalSlider_max")
        self.horizontalSlider_max.setGeometry(QRect(240, 30, 160, 22))
        self.horizontalSlider_max.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(90, 13, 41, 20))
        self.label_7 = QLabel(self.tab_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(290, 13, 51, 20))
        self.btn_mask = QPushButton(self.tab_3)
        self.btn_mask.setObjectName(u"btn_mask")
        self.btn_mask.setGeometry(QRect(20, 190, 81, 23))
        self.label_min = QLabel(self.tab_3)
        self.label_min.setObjectName(u"label_min")
        self.label_min.setGeometry(QRect(135, 13, 47, 21))
        self.label_max = QLabel(self.tab_3)
        self.label_max.setObjectName(u"label_max")
        self.label_max.setGeometry(QRect(335, 13, 47, 20))
        self.chkBox_privRating = QCheckBox(self.tab_3)
        self.chkBox_privRating.setObjectName(u"chkBox_privRating")
        self.chkBox_privRating.setGeometry(QRect(160, 60, 141, 17))
        self.btnSaveMasked = QPushButton(self.tab_3)
        self.btnSaveMasked.setObjectName(u"btnSaveMasked")
        self.btnSaveMasked.setEnabled(False)
        self.btnSaveMasked.setGeometry(QRect(20, 220, 81, 23))
        self.groupBox_4 = QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 80, 451, 91))
        self.chkBox_privRating_two_levels = QCheckBox(self.groupBox_4)
        self.chkBox_privRating_two_levels.setObjectName(u"chkBox_privRating_two_levels")
        self.chkBox_privRating_two_levels.setGeometry(QRect(20, 30, 141, 17))
        self.chkBox_privRating_two_levels.setChecked(False)
        self.label_privacy_rating_second_level = QLabel(self.groupBox_4)
        self.label_privacy_rating_second_level.setObjectName(u"label_privacy_rating_second_level")
        self.label_privacy_rating_second_level.setGeometry(QRect(180, 30, 151, 20))
        self.text_minimum_offset = QTextEdit(self.groupBox_4)
        self.text_minimum_offset.setObjectName(u"text_minimum_offset")
        self.text_minimum_offset.setGeometry(QRect(130, 50, 61, 21))
        self.label_minimum_offset = QLabel(self.groupBox_4)
        self.label_minimum_offset.setObjectName(u"label_minimum_offset")
        self.label_minimum_offset.setGeometry(QRect(20, 50, 111, 20))
        self.label_maximum_offset = QLabel(self.groupBox_4)
        self.label_maximum_offset.setObjectName(u"label_maximum_offset")
        self.label_maximum_offset.setGeometry(QRect(230, 50, 111, 20))
        self.text_maximum_offset = QTextEdit(self.groupBox_4)
        self.text_maximum_offset.setObjectName(u"text_maximum_offset")
        self.text_maximum_offset.setGeometry(QRect(340, 50, 61, 21))
        self.label_privacy_rating_twolevels = QLabel(self.groupBox_4)
        self.label_privacy_rating_twolevels.setObjectName(u"label_privacy_rating_twolevels")
        self.label_privacy_rating_twolevels.setGeometry(QRect(280, 20, 151, 20))
        self.label_privacy_rating = QLabel(self.tab_3)
        self.label_privacy_rating.setObjectName(u"label_privacy_rating")
        self.label_privacy_rating.setGeometry(QRect(300, 60, 151, 20))
        self.label_masking_time = QLabel(self.tab_3)
        self.label_masking_time.setObjectName(u"label_masking_time")
        self.label_masking_time.setGeometry(QRect(250, 190, 151, 20))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_masking_time.setFont(font)
        self.masking_next_pushButton = QPushButton(self.tab_3)
        self.masking_next_pushButton.setObjectName(u"masking_next_pushButton")
        self.masking_next_pushButton.setGeometry(QRect(160, 250, 81, 23))
        self.progressBar = QProgressBar(self.tab_3)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(120, 190, 118, 23))
        self.progressBar.setValue(0)
        self.label_masking_saved = QLabel(self.tab_3)
        self.label_masking_saved.setObjectName(u"label_masking_saved")
        self.label_masking_saved.setGeometry(QRect(120, 220, 221, 20))
        self.label_masking_saved.setFont(font)
        self.btn_saved_masked_layers_loc = QPushButton(self.tab_3)
        self.btn_saved_masked_layers_loc.setObjectName(u"btn_saved_masked_layers_loc")
        self.btn_saved_masked_layers_loc.setEnabled(False)
        self.btn_saved_masked_layers_loc.setGeometry(QRect(360, 220, 31, 23))
        self.tabWidget_4.addTab(self.tab_3, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.horizontalSlider_resolution = QSlider(self.tab_10)
        self.horizontalSlider_resolution.setObjectName(u"horizontalSlider_resolution")
        self.horizontalSlider_resolution.setGeometry(QRect(130, 50, 160, 22))
        self.horizontalSlider_resolution.setOrientation(Qt.Horizontal)
        self.label_8 = QLabel(self.tab_10)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(170, 20, 61, 20))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_resolution = QLabel(self.tab_10)
        self.label_resolution.setObjectName(u"label_resolution")
        self.label_resolution.setGeometry(QRect(230, 20, 31, 20))
        self.btn_bin = QPushButton(self.tab_10)
        self.btn_bin.setObjectName(u"btn_bin")
        self.btn_bin.setGeometry(QRect(140, 130, 131, 23))
        self.binning_next_pushButton = QPushButton(self.tab_10)
        self.binning_next_pushButton.setObjectName(u"binning_next_pushButton")
        self.binning_next_pushButton.setGeometry(QRect(160, 210, 81, 23))
        self.label_binning_saved = QLabel(self.tab_10)
        self.label_binning_saved.setObjectName(u"label_binning_saved")
        self.label_binning_saved.setGeometry(QRect(120, 180, 221, 20))
        self.label_binning_saved.setFont(font)
        self.btnSaveBinned = QPushButton(self.tab_10)
        self.btnSaveBinned.setObjectName(u"btnSaveBinned")
        self.btnSaveBinned.setEnabled(False)
        self.btnSaveBinned.setGeometry(QRect(20, 180, 81, 23))
        self.btn_saved_binned_layers_loc = QPushButton(self.tab_10)
        self.btn_saved_binned_layers_loc.setObjectName(u"btn_saved_binned_layers_loc")
        self.btn_saved_binned_layers_loc.setEnabled(False)
        self.btn_saved_binned_layers_loc.setGeometry(QRect(360, 180, 31, 23))
        self.chkBox_binning_two_levels = QCheckBox(self.tab_10)
        self.chkBox_binning_two_levels.setObjectName(u"chkBox_binning_two_levels")
        self.chkBox_binning_two_levels.setGeometry(QRect(320, 50, 101, 17))
        self.chkBox_binning_two_levels.setChecked(True)
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_encryption = QWidget()
        self.tab_encryption.setObjectName(u"tab_encryption")
        self.btnGeneratePassphrase = QPushButton(self.tab_encryption)
        self.btnGeneratePassphrase.setObjectName(u"btnGeneratePassphrase")
        self.btnGeneratePassphrase.setGeometry(QRect(20, 20, 121, 23))
        self.label_passphrase = QLabel(self.tab_encryption)
        self.label_passphrase.setObjectName(u"label_passphrase")
        self.label_passphrase.setGeometry(QRect(150, 20, 341, 31))
        self.label_passphrase.setAlignment(Qt.AlignCenter)
        self.label_passphrase.setWordWrap(True)
        self.label_enc_vol = QLabel(self.tab_encryption)
        self.label_enc_vol.setObjectName(u"label_enc_vol")
        self.label_enc_vol.setGeometry(QRect(130, 235, 321, 20))
        font1 = QFont()
        font1.setBold(False)
        font1.setWeight(50)
        self.label_enc_vol.setFont(font1)
        self.label_hash_val = QLabel(self.tab_encryption)
        self.label_hash_val.setObjectName(u"label_hash_val")
        self.label_hash_val.setGeometry(QRect(70, 290, 391, 20))
        self.label_hash_val.setFont(font1)
        self.label_passphrase_loc = QLabel(self.tab_encryption)
        self.label_passphrase_loc.setObjectName(u"label_passphrase_loc")
        self.label_passphrase_loc.setGeometry(QRect(130, 262, 321, 20))
        self.label_passphrase_loc.setFont(font1)
        self.btnEncrypt = QPushButton(self.tab_encryption)
        self.btnEncrypt.setObjectName(u"btnEncrypt")
        self.btnEncrypt.setGeometry(QRect(20, 200, 131, 23))
        self.groupBox = QGroupBox(self.tab_encryption)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 70, 481, 121))
        self.groupBox.setFont(font1)
        self.label_osfile_third_level = QLabel(self.groupBox)
        self.label_osfile_third_level.setObjectName(u"label_osfile_third_level")
        self.label_osfile_third_level.setGeometry(QRect(30, 90, 401, 21))
        self.label_osfile_third_level.setLayoutDirection(Qt.LeftToRight)
        self.label_osfile_third_level.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.btn_osfiles_level1 = QPushButton(self.groupBox)
        self.btn_osfiles_level1.setObjectName(u"btn_osfiles_level1")
        self.btn_osfiles_level1.setGeometry(QRect(440, 30, 23, 23))
        self.btn_osfiles_level1.setLayoutDirection(Qt.LeftToRight)
        self.btn_osfiles_level2 = QPushButton(self.groupBox)
        self.btn_osfiles_level2.setObjectName(u"btn_osfiles_level2")
        self.btn_osfiles_level2.setGeometry(QRect(440, 60, 23, 23))
        self.btn_osfiles_level2.setLayoutDirection(Qt.LeftToRight)
        self.btn_osfiles_level3 = QPushButton(self.groupBox)
        self.btn_osfiles_level3.setObjectName(u"btn_osfiles_level3")
        self.btn_osfiles_level3.setGeometry(QRect(440, 90, 23, 23))
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 60, 20, 21))
        self.label_16.setFont(font)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 30, 20, 21))
        self.label_17.setFont(font)
        self.label_osfile_first_level = QLabel(self.groupBox)
        self.label_osfile_first_level.setObjectName(u"label_osfile_first_level")
        self.label_osfile_first_level.setGeometry(QRect(30, 30, 401, 21))
        self.label_osfile_first_level.setLayoutDirection(Qt.LeftToRight)
        self.label_osfile_first_level.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_osfile_second_level = QLabel(self.groupBox)
        self.label_osfile_second_level.setObjectName(u"label_osfile_second_level")
        self.label_osfile_second_level.setGeometry(QRect(30, 60, 401, 21))
        self.label_osfile_second_level.setLayoutDirection(Qt.LeftToRight)
        self.label_osfile_second_level.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 90, 20, 21))
        self.label_15.setFont(font)
        self.label_encryption_time = QLabel(self.tab_encryption)
        self.label_encryption_time.setObjectName(u"label_encryption_time")
        self.label_encryption_time.setGeometry(QRect(180, 200, 141, 20))
        self.label_encryption_time.setFont(font)
        self.label_passphrase_loc_2 = QLabel(self.tab_encryption)
        self.label_passphrase_loc_2.setObjectName(u"label_passphrase_loc_2")
        self.label_passphrase_loc_2.setGeometry(QRect(20, 262, 81, 20))
        self.label_passphrase_loc_2.setFont(font)
        self.label_hash_val_2 = QLabel(self.tab_encryption)
        self.label_hash_val_2.setObjectName(u"label_hash_val_2")
        self.label_hash_val_2.setGeometry(QRect(20, 290, 31, 20))
        self.label_hash_val_2.setFont(font)
        self.label_enc_vol_3 = QLabel(self.tab_encryption)
        self.label_enc_vol_3.setObjectName(u"label_enc_vol_3")
        self.label_enc_vol_3.setGeometry(QRect(20, 235, 121, 20))
        self.label_enc_vol_3.setFont(font)
        self.encryption_next_pushButton = QPushButton(self.tab_encryption)
        self.encryption_next_pushButton.setObjectName(u"encryption_next_pushButton")
        self.encryption_next_pushButton.setGeometry(QRect(350, 200, 75, 23))
        self.btn_enc_volume_location = QPushButton(self.tab_encryption)
        self.btn_enc_volume_location.setObjectName(u"btn_enc_volume_location")
        self.btn_enc_volume_location.setGeometry(QRect(460, 230, 23, 23))
        self.btn_passphrase_location = QPushButton(self.tab_encryption)
        self.btn_passphrase_location.setObjectName(u"btn_passphrase_location")
        self.btn_passphrase_location.setGeometry(QRect(460, 262, 23, 23))
        self.tabWidget_2.addTab(self.tab_encryption, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.button_notarise = QPushButton(self.tab_6)
        self.button_notarise.setObjectName(u"button_notarise")
        self.button_notarise.setGeometry(QRect(20, 180, 131, 23))
        self.label_success = QLabel(self.tab_6)
        self.label_success.setObjectName(u"label_success")
        self.label_success.setEnabled(True)
        self.label_success.setGeometry(QRect(20, 230, 461, 16))
        self.label_tranx = QLabel(self.tab_6)
        self.label_tranx.setObjectName(u"label_tranx")
        self.label_tranx.setGeometry(QRect(240, 180, 141, 20))
        self.label_tranx.setFont(font)
        self.separatefile_notarisation_groupBox = QGroupBox(self.tab_6)
        self.separatefile_notarisation_groupBox.setObjectName(u"separatefile_notarisation_groupBox")
        self.separatefile_notarisation_groupBox.setGeometry(QRect(20, 20, 471, 71))
        self.separatefile_notarisation_groupBox.setFont(font1)
        self.btn_osfile_to_notarise = QPushButton(self.separatefile_notarisation_groupBox)
        self.btn_osfile_to_notarise.setObjectName(u"btn_osfile_to_notarise")
        self.btn_osfile_to_notarise.setGeometry(QRect(440, 27, 23, 23))
        self.btn_osfile_to_notarise.setLayoutDirection(Qt.LeftToRight)
        self.label_osfile_to_notarise = QLabel(self.separatefile_notarisation_groupBox)
        self.label_osfile_to_notarise.setObjectName(u"label_osfile_to_notarise")
        self.label_osfile_to_notarise.setGeometry(QRect(10, 30, 421, 21))
        self.label_osfile_to_notarise.setLayoutDirection(Qt.LeftToRight)
        self.label_osfile_to_notarise.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_osfile_to_notarise.raise_()
        self.btn_osfile_to_notarise.raise_()
        self.label_final_encrypted_volume_text = QLabel(self.tab_6)
        self.label_final_encrypted_volume_text.setObjectName(u"label_final_encrypted_volume_text")
        self.label_final_encrypted_volume_text.setGeometry(QRect(20, 100, 131, 20))
        self.label_final_encrypted_volume_text.setFont(font)
        self.label_hash_value = QLabel(self.tab_6)
        self.label_hash_value.setObjectName(u"label_hash_value")
        self.label_hash_value.setGeometry(QRect(90, 130, 391, 20))
        self.label_final_encrypted_volume_notarise = QLabel(self.tab_6)
        self.label_final_encrypted_volume_notarise.setObjectName(u"label_final_encrypted_volume_notarise")
        self.label_final_encrypted_volume_notarise.setGeometry(QRect(160, 100, 321, 20))
        self.label_hash_value_text = QLabel(self.tab_6)
        self.label_hash_value_text.setObjectName(u"label_hash_value_text")
        self.label_hash_value_text.setGeometry(QRect(20, 130, 141, 20))
        self.label_hash_value_text.setFont(font)
        self.label_tranx_url = QLabel(self.tab_6)
        self.label_tranx_url.setObjectName(u"label_tranx_url")
        self.label_tranx_url.setEnabled(True)
        self.label_tranx_url.setGeometry(QRect(20, 260, 461, 31))
        self.label_tranx_url.setOpenExternalLinks(False)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.safeguard_progressBar = QProgressBar(self.tab)
        self.safeguard_progressBar.setObjectName(u"safeguard_progressBar")
        self.safeguard_progressBar.setGeometry(QRect(70, 30, 361, 16))
        self.safeguard_progressBar.setValue(24)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(120, 10, 67, 13))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(230, 10, 47, 13))
        self.label_3.setFont(font)
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(350, 10, 55, 13))
        self.label_9.setFont(font)
        self.label_safeguard_options = QLabel(self.tab)
        self.label_safeguard_options.setObjectName(u"label_safeguard_options")
        self.label_safeguard_options.setGeometry(QRect(70, 20, 331, 31))
        self.label_safeguard_options.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_3 = QTabWidget(self.tab_2)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(10, 60, 491, 401))
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.lbl_hash_value = QLabel(self.tab_7)
        self.lbl_hash_value.setObjectName(u"lbl_hash_value")
        self.lbl_hash_value.setGeometry(QRect(30, 170, 551, 20))
        self.label_5 = QLabel(self.tab_7)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 140, 421, 20))
        self.btn_upload_encrypted_vol = QPushButton(self.tab_7)
        self.btn_upload_encrypted_vol.setObjectName(u"btn_upload_encrypted_vol")
        self.btn_upload_encrypted_vol.setGeometry(QRect(30, 40, 141, 23))
        self.label_encrypted_volume = QLabel(self.tab_7)
        self.label_encrypted_volume.setObjectName(u"label_encrypted_volume")
        self.label_encrypted_volume.setGeometry(QRect(30, 80, 471, 21))
        self.label_encrypted_volume.setLayoutDirection(Qt.LeftToRight)
        self.label_encrypted_volume.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.verify_next_pushButton = QPushButton(self.tab_7)
        self.verify_next_pushButton.setObjectName(u"verify_next_pushButton")
        self.verify_next_pushButton.setGeometry(QRect(190, 210, 75, 23))
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.rbt_level3 = QRadioButton(self.tab_8)
        self.rbt_level3.setObjectName(u"rbt_level3")
        self.rbt_level3.setGeometry(QRect(310, 130, 151, 17))
        self.btn_readPassphrase = QPushButton(self.tab_8)
        self.btn_readPassphrase.setObjectName(u"btn_readPassphrase")
        self.btn_readPassphrase.setGeometry(QRect(10, 40, 121, 23))
        self.btnDecrypt = QPushButton(self.tab_8)
        self.btnDecrypt.setObjectName(u"btnDecrypt")
        self.btnDecrypt.setGeometry(QRect(10, 190, 131, 23))
        self.rbt_level1 = QRadioButton(self.tab_8)
        self.rbt_level1.setObjectName(u"rbt_level1")
        self.rbt_level1.setGeometry(QRect(30, 130, 101, 17))
        self.label_4 = QLabel(self.tab_8)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 100, 151, 16))
        self.rbt_level2 = QRadioButton(self.tab_8)
        self.rbt_level2.setObjectName(u"rbt_level2")
        self.rbt_level2.setEnabled(True)
        self.rbt_level2.setGeometry(QRect(160, 130, 151, 17))
        self.txt_passphrase = QTextEdit(self.tab_8)
        self.txt_passphrase.setObjectName(u"txt_passphrase")
        self.txt_passphrase.setGeometry(QRect(140, 40, 341, 41))
        self.label_decrypted_volume = QLabel(self.tab_8)
        self.label_decrypted_volume.setObjectName(u"label_decrypted_volume")
        self.label_decrypted_volume.setGeometry(QRect(20, 220, 421, 20))
        self.label_decrypted_volume.setFont(font1)
        self.label_decryption_time = QLabel(self.tab_8)
        self.label_decryption_time.setObjectName(u"label_decryption_time")
        self.label_decryption_time.setGeometry(QRect(170, 190, 151, 20))
        self.label_decryption_time.setFont(font)
        self.btn_open_decrypted_folder = QPushButton(self.tab_8)
        self.btn_open_decrypted_folder.setObjectName(u"btn_open_decrypted_folder")
        self.btn_open_decrypted_folder.setGeometry(QRect(510, 220, 23, 23))
        self.decrypt_next_pushButton = QPushButton(self.tab_8)
        self.decrypt_next_pushButton.setObjectName(u"decrypt_next_pushButton")
        self.decrypt_next_pushButton.setGeometry(QRect(190, 260, 75, 23))
        self.btn_dec_volume_location = QPushButton(self.tab_8)
        self.btn_dec_volume_location.setObjectName(u"btn_dec_volume_location")
        self.btn_dec_volume_location.setGeometry(QRect(460, 220, 23, 23))
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.btn_displaymap = QPushButton(self.tab_9)
        self.btn_displaymap.setObjectName(u"btn_displaymap")
        self.btn_displaymap.setGeometry(QRect(170, 270, 131, 23))
        self.treeWidget = QTreeWidget(self.tab_9)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(50, 20, 401, 231))
        self.tabWidget_3.addTab(self.tab_9, "")
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(350, 10, 55, 13))
        self.label_10.setFont(font)
        self.verification_progressBar = QProgressBar(self.tab_2)
        self.verification_progressBar.setObjectName(u"verification_progressBar")
        self.verification_progressBar.setGeometry(QRect(70, 30, 361, 16))
        self.verification_progressBar.setValue(24)
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(130, 10, 67, 13))
        self.label_11.setFont(font)
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(230, 10, 57, 13))
        self.label_12.setFont(font)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox_2 = QGroupBox(self.tab_5)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 120, 481, 101))
        self.groupBox_2.setFont(font)
        self.label_encrypted_passphrase_file = QLabel(self.groupBox_2)
        self.label_encrypted_passphrase_file.setObjectName(u"label_encrypted_passphrase_file")
        self.label_encrypted_passphrase_file.setGeometry(QRect(130, 70, 351, 20))
        self.label_encrypted_passphrase_file.setFont(font)
        self.btn_select_passphrase_file = QPushButton(self.groupBox_2)
        self.btn_select_passphrase_file.setObjectName(u"btn_select_passphrase_file")
        self.btn_select_passphrase_file.setGeometry(QRect(10, 30, 101, 25))
        self.btn_select_passphrase_file.setFont(font1)
        self.btn_select_public_key = QPushButton(self.groupBox_2)
        self.btn_select_public_key.setObjectName(u"btn_select_public_key")
        self.btn_select_public_key.setGeometry(QRect(140, 30, 121, 25))
        self.btn_select_public_key.setFont(font1)
        self.btn_encrypt_passphrase = QPushButton(self.groupBox_2)
        self.btn_encrypt_passphrase.setObjectName(u"btn_encrypt_passphrase")
        self.btn_encrypt_passphrase.setGeometry(QRect(290, 30, 121, 25))
        self.btn_encrypt_passphrase.setFont(font1)
        self.label_encrypted_passphrase = QLabel(self.groupBox_2)
        self.label_encrypted_passphrase.setObjectName(u"label_encrypted_passphrase")
        self.label_encrypted_passphrase.setGeometry(QRect(10, 70, 131, 20))
        self.label_encrypted_passphrase.setFont(font1)
        self.btn_enc_passphrase_loc = QPushButton(self.groupBox_2)
        self.btn_enc_passphrase_loc.setObjectName(u"btn_enc_passphrase_loc")
        self.btn_enc_passphrase_loc.setGeometry(QRect(550, 70, 23, 23))
        self.groupBox_3 = QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 250, 481, 101))
        self.groupBox_3.setFont(font)
        self.label_decrypted_passphrase_file = QLabel(self.groupBox_3)
        self.label_decrypted_passphrase_file.setObjectName(u"label_decrypted_passphrase_file")
        self.label_decrypted_passphrase_file.setGeometry(QRect(130, 70, 351, 20))
        self.btn_select_encrypted_passphrase_file = QPushButton(self.groupBox_3)
        self.btn_select_encrypted_passphrase_file.setObjectName(u"btn_select_encrypted_passphrase_file")
        self.btn_select_encrypted_passphrase_file.setGeometry(QRect(10, 30, 101, 25))
        self.btn_select_encrypted_passphrase_file.setFont(font1)
        self.btn_select_private_key = QPushButton(self.groupBox_3)
        self.btn_select_private_key.setObjectName(u"btn_select_private_key")
        self.btn_select_private_key.setGeometry(QRect(140, 30, 121, 25))
        self.btn_select_private_key.setFont(font1)
        self.btn_decrypt_passphrase = QPushButton(self.groupBox_3)
        self.btn_decrypt_passphrase.setObjectName(u"btn_decrypt_passphrase")
        self.btn_decrypt_passphrase.setGeometry(QRect(290, 30, 121, 23))
        self.btn_decrypt_passphrase.setFont(font1)
        self.label_decrypted_passphrase = QLabel(self.groupBox_3)
        self.label_decrypted_passphrase.setObjectName(u"label_decrypted_passphrase")
        self.label_decrypted_passphrase.setGeometry(QRect(10, 70, 131, 20))
        self.label_decrypted_passphrase.setFont(font1)
        self.btn_dec_passphrase_loc = QPushButton(self.groupBox_3)
        self.btn_dec_passphrase_loc.setObjectName(u"btn_dec_passphrase_loc")
        self.btn_dec_passphrase_loc.setGeometry(QRect(550, 70, 23, 23))
        self.groupBox_5 = QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 20, 481, 80))
        self.groupBox_5.setFont(font)
        self.label_generated_key_pair = QLabel(self.groupBox_5)
        self.label_generated_key_pair.setObjectName(u"label_generated_key_pair")
        self.label_generated_key_pair.setGeometry(QRect(10, 50, 111, 20))
        self.label_generated_key_pair.setFont(font1)
        self.btn_generate_keys = QPushButton(self.groupBox_5)
        self.btn_generate_keys.setObjectName(u"btn_generate_keys")
        self.btn_generate_keys.setGeometry(QRect(290, 24, 121, 23))
        self.btn_generate_keys.setFont(font1)
        self.btn_generated_passphrase = QPushButton(self.groupBox_5)
        self.btn_generated_passphrase.setObjectName(u"btn_generated_passphrase")
        self.btn_generated_passphrase.setGeometry(QRect(550, 50, 23, 23))
        self.label_generated_keys = QLabel(self.groupBox_5)
        self.label_generated_keys.setObjectName(u"label_generated_keys")
        self.label_generated_keys.setGeometry(QRect(130, 50, 351, 20))
        self.label_generated_keys.setFont(font)
        self.label_generated_key_pair_2 = QLabel(self.groupBox_5)
        self.label_generated_key_pair_2.setObjectName(u"label_generated_key_pair_2")
        self.label_generated_key_pair_2.setGeometry(QRect(10, 24, 281, 20))
        self.label_generated_key_pair_2.setFont(font1)
        self.tabWidget.addTab(self.tab_5, "")
        self.label_working_dir = QLabel(BulkVectorExportDialogBase)
        self.label_working_dir.setObjectName(u"label_working_dir")
        self.label_working_dir.setGeometry(QRect(340, 10, 191, 21))
        self.label_working_dir.setFrameShape(QFrame.Box)
        self.label_working_dir.setFrameShadow(QFrame.Sunken)
        self.btnENVFileDir = QPushButton(BulkVectorExportDialogBase)
        self.btnENVFileDir.setObjectName(u"btnENVFileDir")
        self.btnENVFileDir.setGeometry(QRect(373, 33, 91, 23))
        self.label_working_dir_text = QLabel(BulkVectorExportDialogBase)
        self.label_working_dir_text.setObjectName(u"label_working_dir_text")
        self.label_working_dir_text.setGeometry(QRect(277, 12, 57, 13))
        self.label_working_dir_text.setFont(font1)
        self.btn_help = QPushButton(BulkVectorExportDialogBase)
        self.btn_help.setObjectName(u"btn_help")
        self.btn_help.setGeometry(QRect(470, 33, 61, 23))

        self.retranslateUi(BulkVectorExportDialogBase)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(BulkVectorExportDialogBase)
    # setupUi

    def retranslateUi(self, BulkVectorExportDialogBase):
        BulkVectorExportDialogBase.setWindowTitle(QCoreApplication.translate("BulkVectorExportDialogBase", u"MapSafe QGIS Plugin", None))
        self.label_6.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Minimum", None))
        self.label_7.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Maximum", None))
        self.btn_mask.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Mask", None))
        self.label_min.setText("")
        self.label_max.setText("")
        self.chkBox_privRating.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Compute Privacy Rating", None))
        self.btnSaveMasked.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Save layers", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("BulkVectorExportDialogBase", u"Mask at Two levels", None))
        self.chkBox_privRating_two_levels.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Two levels", None))
        self.label_privacy_rating_second_level.setText("")
        self.text_minimum_offset.setPlaceholderText("")
        self.label_minimum_offset.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Minimum value offset", None))
        self.label_maximum_offset.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Maximum value offset", None))
        self.text_maximum_offset.setPlaceholderText("")
        self.label_privacy_rating_twolevels.setText("")
        self.label_privacy_rating.setText("")
        self.label_masking_time.setText("")
        self.masking_next_pushButton.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Next", None))
        self.label_masking_saved.setText("")
        self.btn_saved_masked_layers_loc.setText("")
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_3), QCoreApplication.translate("BulkVectorExportDialogBase", u"Masking", None))
        self.label_8.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Resolution", None))
        self.label_resolution.setText("")
        self.btn_bin.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Bin", None))
        self.binning_next_pushButton.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Next", None))
        self.label_binning_saved.setText("")
        self.btnSaveBinned.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Save layers", None))
        self.btn_saved_binned_layers_loc.setText("")
        self.chkBox_binning_two_levels.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Two levels", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), QCoreApplication.translate("BulkVectorExportDialogBase", u"Hexabinning", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("BulkVectorExportDialogBase", u"Anonymisation ", None))
        self.btnGeneratePassphrase.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Generate Passphrase", None))
        self.label_passphrase.setText("")
        self.label_enc_vol.setText("")
        self.label_hash_val.setText("")
        self.label_passphrase_loc.setText("")
        self.btnEncrypt.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Encrypt", None))
        self.groupBox.setTitle(QCoreApplication.translate("BulkVectorExportDialogBase", u"Choose Files to Encrypt", None))
        self.label_osfile_third_level.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Choose File", None))
        self.btn_osfiles_level1.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"...", None))
        self.btn_osfiles_level2.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"...", None))
        self.btn_osfiles_level3.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"...", None))
        self.label_16.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"2.", None))
        self.label_17.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"1.", None))
        self.label_osfile_first_level.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Choose File", None))
        self.label_osfile_second_level.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Choose File", None))
        self.label_15.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"3.", None))
        self.label_encryption_time.setText("")
        self.label_passphrase_loc_2.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Passphrase:", None))
        self.label_hash_val_2.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Hash: ", None))
        self.label_enc_vol_3.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Encrypted volume:", None))
        self.encryption_next_pushButton.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Next", None))
        self.btn_enc_volume_location.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"...", None))
        self.btn_passphrase_location.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"...", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_encryption), QCoreApplication.translate("BulkVectorExportDialogBase", u"Encryption", None))
        self.button_notarise.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Notarise ", None))
        self.label_success.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"The filename and hash value is being notarised on the Ethereum Blockchain at the following URL: ", None))
        self.label_tranx.setText("")
        self.separatefile_notarisation_groupBox.setTitle(QCoreApplication.translate("BulkVectorExportDialogBase", u"Select an original, anonymised, or encrypted file to notarise", None))
        self.btn_osfile_to_notarise.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"...", None))
        self.label_osfile_to_notarise.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Choose File", None))
        self.label_final_encrypted_volume_text.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Final encypted volume:", None))
        self.label_hash_value.setText("")
        self.label_final_encrypted_volume_notarise.setText("")
        self.label_hash_value_text.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Hash Value", None))
        self.label_tranx_url.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("BulkVectorExportDialogBase", u"Notarisation", None))
        self.label_2.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Anonymise", None))
        self.label_3.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Encrypt", None))
        self.label_9.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Notarise", None))
        self.label_safeguard_options.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("BulkVectorExportDialogBase", u"Safeguard", None))
        self.lbl_hash_value.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Hash Value", None))
        self.label_5.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Encrypted volume's hash value for comparison with the value on blockchain:", None))
        self.btn_upload_encrypted_vol.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Upload Encrypted Volume", None))
        self.label_encrypted_volume.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Choose File", None))
        self.verify_next_pushButton.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Next", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("BulkVectorExportDialogBase", u"Verify", None))
        self.rbt_level3.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Level 3 (More Anonymised)", None))
        self.btn_readPassphrase.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Read Passphrase File", None))
        self.btnDecrypt.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Decrypt", None))
        self.rbt_level1.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Level 1 (Original)", None))
        self.label_4.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Choose Level to Decrypt to:", None))
        self.rbt_level2.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Level 2 (Anonymised)", None))
        self.label_decrypted_volume.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Decrypted volume:", None))
        self.label_decryption_time.setText("")
        self.btn_open_decrypted_folder.setText("")
        self.decrypt_next_pushButton.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Next", None))
        self.btn_dec_volume_location.setText("")
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("BulkVectorExportDialogBase", u"Decryption", None))
        self.btn_displaymap.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Display", None))
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("BulkVectorExportDialogBase", u"Decrypted Levels", None));
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), QCoreApplication.translate("BulkVectorExportDialogBase", u"Display", None))
        self.label_10.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Display", None))
        self.label_11.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Verify", None))
        self.label_12.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Decrypt", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("BulkVectorExportDialogBase", u"Verification", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("BulkVectorExportDialogBase", u"Encrypt Passphrase file", None))
        self.label_encrypted_passphrase_file.setText("")
        self.btn_select_passphrase_file.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Select  file", None))
        self.btn_select_public_key.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Select Public Key", None))
        self.btn_encrypt_passphrase.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Encrypt", None))
        self.label_encrypted_passphrase.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Encrypted passphrase:", None))
        self.btn_enc_passphrase_loc.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("BulkVectorExportDialogBase", u"Decrypt Passphrase file", None))
        self.label_decrypted_passphrase_file.setText("")
        self.btn_select_encrypted_passphrase_file.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Select file", None))
        self.btn_select_private_key.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Select Private Key", None))
        self.btn_decrypt_passphrase.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Decrypt", None))
        self.label_decrypted_passphrase.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Decrypted passphrase:", None))
        self.btn_dec_passphrase_loc.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("BulkVectorExportDialogBase", u"Generate Public and Private keys", None))
        self.label_generated_key_pair.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Key Pair:", None))
        self.btn_generate_keys.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Generate", None))
        self.btn_generated_passphrase.setText("")
        self.label_generated_keys.setText("")
        self.label_generated_key_pair_2.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Data senders and recipients need to generate this once.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("BulkVectorExportDialogBase", u"Shield Passphrase", None))
        self.label_working_dir.setText("")
        self.btnENVFileDir.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Set ENV values", None))
        self.label_working_dir_text.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Working dir", None))
        self.btn_help.setText(QCoreApplication.translate("BulkVectorExportDialogBase", u"Help", None))
    # retranslateUi

